Dev
Nkaka23dev/the-gym-KMarkerter-clone pull request #1
Opened 2022-09-28 09:03 UTC by Nkaka23dev

2022-09-28 17:19 UTC, NNesta requested changes

2022-09-28 17:19 UTC, NNesta commented on responsive.css
> +        margin-top: 4rem;
You should name using descriptive name

2022-09-28 17:19 UTC, NNesta commented on responsive.css
> +    .p-text {
You should name using descriptive name

2022-09-28 17:19 UTC, NNesta commented on responsive.css
> +    .form_text {
This is not BEM

2022-09-28 17:19 UTC, NNesta commented on responsive.css
> +        margin-top: 1.5rem;
This modifier does not modify what it is named for

2022-09-29 09:06 UTC, sezeranoJchrisostome requested changes
Well done @Nkaka23dev, I left some comments you can take look at it. 👍👌

2022-09-29 09:06 UTC, chrisostome01 commented on responsive.css
> +    /* .v-container__btn {
You can remove this commented style

2022-09-29 09:06 UTC, chrisostome01 commented on responsive.css
> +
Try to avoid unnecessary spaces in your CSS,

2022-09-29 09:06 UTC, chrisostome01 commented on main.css
> +.items {
May you try to place this Item after navbar, for better structure

2022-09-29 10:04 UTC, sezeranoJchrisostome approved these changes
Well done

2022-09-29 10:04 UTC, chrisostome01 commented on index.html
> +                    <div class="client-card">
Well done @Nkaka23dev, now i think it is easy, to modify this card's content

2022-09-29 10:18 UTC, NNesta approved these changes
Nice done @Nkaka23dev

2022-09-29 14:52 UTC, karemarsy commented on main.css
> +input[type=submit]:hover {
this is not BEM

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +        <div class="navbar-container__menu-items-sm">
`navbar-container__menu-items-sm` is positioned outside the Block `(navbar-container)`.

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +                <span class="navbar-container__item">Home</span>
`navbar-container__item` is positioned outside the Block `(navbar-container)`.

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +            <div class="page-text__sub-txt">
`page-text__sub-txt` is positioned outside the Block `(page-text)`.

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +                <div class="page-text__sub-txt page-text__sub-txt--sm">
`page-text__sub-txt` is positioned outside the Block `(page-text).` and also
`page-text__sub-txt--sm `is positioned outside the Block `(page-text)`.

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +                    <p class="p-text p-text--sm p-text-sm--normal">We are providing best <br> <span>business
`p-text-sm--normal` is included without it's default Element `p-text-sm.`

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +                    <p class="p-text p-text--sm p-text-sm--normal">What Clients says</span> </p>
`p-text-sm--normal` is included without it's default Element `p-text-sm.`

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +                    <p class="p-text p-text--sm p-text-sm--normal">Meet Our Team</p>
`p-text-sm--norma`l is included without it's default Element `p-text-sm.`

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +            <div class="card__wrapper">
`card__wrapper` is positioned outside the Block `card`.

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +                    <h2 class="logo--white">KMarketer</h2>
`logo--white` is included without its default Element `logo.`

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +                    <h1 class="logo logo--white logo--sm">Made With Love By <br class="separator"> Figma Land All Right
`logo--white` is included without its default Element `logo.`

2022-09-29 14:52 UTC, karemarsy commented on index.html
> +            <div class="footer__content footer-content--unbordered">
`footer-content--unbordered` is included without it's default Element `footer-content`.

2022-09-29 16:51 UTC, NNesta requested changes

2022-09-29 16:51 UTC, NNesta commented on index.html
> +                        <p>Carrier</p>
remove that typo <p c>

2022-09-29 16:51 UTC, NNesta commented on index.html
> +                        <p>We are hiring</p>
remove typo <p c>

2022-09-29 16:53 UTC, sezeranoJchrisostome requested changes
Well done @Nkaka23dev, I left some comments for you, try to work on them.

2022-09-29 16:53 UTC, sezeranoJchrisostome commented on main.css
> +.col-75 {
It would be better if rename this block with meaningful name

2022-09-29 16:53 UTC, sezeranoJchrisostome commented on main.css
> +.logo--sm {
To structure your css it is better to put your block, block element, and modifier in the same places for instance you can have this `logo--sm` in the same place as where you defined your block

2022-09-29 17:31 UTC, sezeranoJchrisostome approved these changes
LGTM 👍👍

2022-09-29 17:33 UTC, NNesta approved these changes
LGTM

2022-10-04 13:56 UTC, karemarsy approved these changes

2022-10-10 10:28 UTC, merged